extends:
  - 'standard-with-typescript'

parserOptions:
  project: './tsconfig.eslint.json'

overrides:
  - files: '**/*.test.*'
    env:
      mocha: true
    rules:
      no-unused-expressions: off
      '@typescript-eslint/no-unused-expressions': off
